#!/usr/bin/env python3
"""Regenerate imagechanger/neutral_tile.py: a flat 512x512 Main10 4:2:0 HEVC still.

Needs ffmpeg with libx265. The result is the "no correction" tile used for every cell of
the style delta map (decoded Y=504, Cb=Cr=512 in 10-bit, no VUI, like native tiles).
"""
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
from imagechanger.bmff import find_box, iter_boxes  # noqa: E402


MAIN10_PTL = bytes.fromhex("0220000000900000000000")   # idc, compat flags, 6 constraint bytes (11 B)


def unescape(nal: bytes) -> bytes:
    out, zeros = bytearray(), 0
    for b in nal:
        if zeros >= 2 and b == 3:
            zeros = 0
            continue
        out.append(b)
        zeros = zeros + 1 if b == 0 else 0
    return bytes(out)


def escape(rbsp: bytes) -> bytes:
    out, zeros = bytearray(), 0
    for b in rbsp:
        if zeros >= 2 and b <= 3:
            out.append(3)
            zeros = 0
        out.append(b)
        zeros = zeros + 1 if b == 0 else 0
    return bytes(out)


def to_main10(nal: bytes) -> bytes:
    """Rewrite the general profile fields of a VPS/SPS NAL from Rext (4) to Main 10 (2)."""
    kind = (nal[0] >> 1) & 63
    r = bytearray(unescape(nal))
    at = {32: 6, 33: 3}[kind]          # VPS: 2 hdr + 4 fixed bytes; SPS: 2 hdr + 1 byte
    assert r[at] & 31 == 4, "expected a Rext profile_idc"
    r[at:at + 11] = MAIN10_PTL
    return escape(bytes(r))


def patch_hvcc(hvcc: bytes) -> bytes:
    """hvcC with Main 10 profile fields and VPS/SPS rewritten (PPS untouched)."""
    h = bytearray(hvcC_body := hvcc[8:])
    h[1:12] = MAIN10_PTL
    p, out = 23, bytearray(h[:23])
    for _ in range(h[22]):
        kind, cnt = h[p] , int.from_bytes(h[p + 1:p + 3], "big")
        out += h[p:p + 3]
        p += 3
        for _n in range(cnt):
            ln = int.from_bytes(h[p:p + 2], "big")
            nal = bytes(h[p + 2:p + 2 + ln])
            if (kind & 63) in (32, 33):
                nal = to_main10(nal)
            out += len(nal).to_bytes(2, "big") + nal
            p += 2 + ln
    return (8 + len(out)).to_bytes(4, "big") + b"hvcC" + bytes(out)


def vcl_only(sample: bytes) -> bytes:
    """Length-prefixed sample reduced to its VCL NAL units (parameter sets live in hvcC)."""
    out, q = b"", 0
    while q < len(sample):
        ln = int.from_bytes(sample[q:q + 4], "big")
        if ((sample[q + 4] >> 1) & 63) < 32:
            out += sample[q:q + 4 + ln]
        q += 4 + ln
    return out


def find_path(buf, path, start=0, end=None):
    for kind in path:
        hit = find_box(buf, kind, start, end)
        if hit is None:
            raise SystemExit(f"missing {kind!r}")
        b0, p0, b1 = hit
        start, end = p0, b1
    return b0, p0, b1


def main():
    with tempfile.TemporaryDirectory() as tmp:
        mp4 = Path(tmp) / "tile.mp4"
        subprocess.run([
            "ffmpeg", "-v", "error", "-y", "-f", "lavfi", "-i",
            "color=c=black:s=512x512:r=1,format=yuv420p10le,geq=lum=504:cb=512:cr=512",
            "-frames:v", "1", "-c:v", "libx265", "-pix_fmt", "yuv420p10le",
            "-x265-params", "log-level=none:keyint=1:profile=main10:no-sao=1:no-deblock=1:no-info=1", "-tag:v", "hvc1", "-f", "mp4", str(mp4)],
            check=True)
        buf = mp4.read_bytes()
    _b0, stsd_p, stsd_end = find_path(buf, [b"moov", b"trak", b"mdia", b"minf", b"stbl", b"stsd"])
    entry = stsd_p + 8                       # FullBox header + entry_count
    esize = int.from_bytes(buf[entry:entry + 4], "big")
    hv0, hvp, hv1 = find_box(buf, b"hvcC", entry + 8 + 78, entry + esize)
    hvcc = patch_hvcc(buf[hv0:hv1])
    mdat = find_box(buf, b"mdat")
    sample = vcl_only(buf[mdat[1]:mdat[2]])
    out = ROOT / "imagechanger" / "neutral_tile.py"
    out.write_text(
        '"""Generated by tools/gen_neutral_tile.py - do not edit."""\n'
        f"HVCC = bytes.fromhex(\n    \"{hvcc.hex()}\")\n"
        f"SAMPLE = bytes.fromhex(\n    \"{sample.hex()}\")\n")
    print(f"wrote {out}: hvcC {len(hvcc)} B, sample {len(sample)} B")


if __name__ == "__main__":
    main()
