#!/usr/bin/env python3
"""Regenerate imagechanger/matte_tile.py: an all-zero 768x576 8-bit monochrome HEVC still.

Used as the "empty" content of the twelve 2026 semantic matte items (needs ffmpeg + libx265).
"""
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "tools"))
from gen_neutral_tile import find_path, vcl_only  # noqa: E402
from imagechanger.bmff import find_box           # noqa: E402


def main():
    with tempfile.TemporaryDirectory() as tmp:
        mp4 = Path(tmp) / "m.mp4"
        subprocess.run([
            "ffmpeg", "-v", "error", "-y", "-f", "lavfi", "-i", "color=c=black:s=768x576:r=1,format=gray,geq=lum=0",
            "-frames:v", "1", "-c:v", "libx265", "-pix_fmt", "gray", "-color_range", "pc",
            "-x265-params", "log-level=none:keyint=1:no-info=1:range=full", "-tag:v", "hvc1", "-f", "mp4", str(mp4)],
            check=True)
        buf = mp4.read_bytes()
    _b0, stsd_p, _e = find_path(buf, [b"moov", b"trak", b"mdia", b"minf", b"stbl", b"stsd"])
    entry = stsd_p + 8
    esize = int.from_bytes(buf[entry:entry + 4], "big")
    hv0, _hp, hv1 = find_box(buf, b"hvcC", entry + 8 + 78, entry + esize)
    hvcc = buf[hv0:hv1]
    mdat = find_box(buf, b"mdat")
    sample = vcl_only(buf[mdat[1]:mdat[2]])
    out = ROOT / "imagechanger" / "matte_tile.py"
    out.write_text('"""Generated by tools/gen_matte_tile.py - do not edit."""\n'
                   f'HVCC = bytes.fromhex(\n    "{hvcc.hex()}")\n'
                   f'SAMPLE = bytes.fromhex(\n    "{sample.hex()}")\n')
    print(f"wrote {out}: hvcC {len(hvcc)} B, sample {len(sample)} B; "
          f"chroma_format_idc={hvcc[8 + 16] & 3} bitdepth={(hvcc[8 + 17] & 7) + 8}")


if __name__ == "__main__":
    main()
